AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sam-directory-test-hello
      CodeUri: functions/
      Handler: hello.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
  SendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sam-directory-test-send
      CodeUri: functions/
      Handler: send.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
